version: '3.8'

services:
 drupal:
  image: drupal:latest
  ports:
   - 8081:80
  volumes:
   - /var/www/html/modules
   - /var/www/html/profiles
   - /var/www/html/themes
   - /var/www/html/sites
  restart: always

 drupaldb:
  image: mysql:latest
  command: --default-authentication-plugin=mysql_native_password
  ports:
   - 3306:3306
  environment:
   MYSQL_DATABASE: drupaldb
   MYSQL_ROOT_PASSWORD: admin
  volumes:
    - C:\Users\Medac\Desktop\Montaje:/var/lib/mysql
  restart: always